[package]
name = "kashida"
version = "0.1.0"
edition = "2021"

[dependencies]
constcat = "0.5.0"
hashbrown = "0.14.5"
icu_segmenter = "1.4.0"
itertools = { version = "0.12", default-features = false }
